package com.explore.rest.utils;

import com.explore.rest.dto.CourseRequestDTO;
import com.explore.rest.dto.CourseResponseDTO;
import com.explore.rest.entity.CourseEntity;

public class AppUtils {
    //utility class which takes dto as input  and converts it into entity
 //   dto --> entity

    public  static CourseEntity mapDTOToEntity(CourseRequestDTO courseRequestDTO){
        CourseEntity courseEntity = new CourseEntity(); //here id will be auto generated by JPA we don't need to set it explicitly
        courseEntity.setName(courseRequestDTO.getName());
        courseEntity.setTrainerName(courseRequestDTO.getTrainerName());
        courseEntity.setDuration(courseRequestDTO.getDuration());
        courseEntity.setStartDate(courseRequestDTO.getStartDate());
        courseEntity.setCourseType(courseRequestDTO.getCourseType());
        courseEntity.setFees(courseRequestDTO.getFees());
        courseEntity.setCertificateAvailable(courseRequestDTO.isCertificateAvailable());

//        courseEntity.setEmailId(courseRequestDTO.getEmailId());
//        courseEntity.setContact(courseRequestDTO.getContact());
        return courseEntity;

//        CourseEntity courseEntity=new CourseEntity();
        /*courseEntity.setCourseName(courseEntity.getCourseName());
        courseEntity.setFees(courseEntity.getFees());*/
    }

    public  static CourseResponseDTO mapEntityToDTO(CourseEntity courseEntity){
        CourseResponseDTO courseResponseDTO = new CourseResponseDTO();
        courseResponseDTO.setCourseId(courseEntity.getCourseId());
        courseResponseDTO.setName(courseEntity.getName());
        courseResponseDTO.setTrainerName(courseEntity.getTrainerName());
        courseResponseDTO.setDuration(courseEntity.getDuration());
        courseResponseDTO.setStartDate(courseEntity.getStartDate());
        courseResponseDTO.setCourseType(courseEntity.getCourseType());
        courseResponseDTO.setFees(courseEntity.getFees());
        courseResponseDTO.setCertificateAvailable(courseEntity.isCertificateAvailable());
        /*courseResponseDTO.setEmailId(courseEntity.getEmailId());
        courseResponseDTO.setContact(courseEntity.getContact());*/
        return courseResponseDTO;

    }
}
